build:
  #fvm, shorebird, default
  method: default
  android:
    #optional, if you need to pass any arguments to build command, like using a specific -t target, or shorebird configuration
    # like --flutter-version or any other stuff
    build_args: null
    #optional
    apk_path: null
    #optional
    bundle_path: null
    #if cloud not given will only build
    gcloud:
      bucket: flavor1-bucket
      app_id: flavor1-app-id
  ios:
    #optional, if you need to pass any arguments to build command, like using a specific -t target, or shorebird configuration
    # like --flutter-version or any other stuff
    build_args: 
    #if not given will only build the ipa file, will search in build/ios/ipa
    ipa_name: null
  #optional
  flavors:
    #by using a default if you call the package build function, will use the according flavor, the value must be a valid flavor name
    default_build: null
    dev:
      #fvm, shorebird, default
      method: default
      android:
        #to pass flavor flags and all stuffs, dont need to pass --flavor dev because its implicit
        build_args: -t lib/main_dev.dart
        #required  generaly flavors change build file name
        apk_name: 
        #optional
        apk_path: null
        #generaly flavors change build file name
        bundle_name:
        #optional
        bundle_path: null
        #if you want to use custom email put in build.env archive DEV_ANDROID_EMAIL, this email must to have access to this gcloud
        #if cloud not given will only build
        gcloud:
          bucket: flavor1-bucket
          app_id: flavor1-app-id

      ios:
        #to pass flavor flags and all stuffs, dont need to pass --flavor dev because its implicit
        build_args: -t lib/main_dev.dart
        #if not given will only build the ipa file, will search in build/ios/ipa
        ipa_name: null


#optional, if given will send a message with android uploaded link
discord:
  #required
  webhook_url: YOUR_DISCORD_WEBHOOK_URL
  #optional, will tag the channel in the message
  channel_id: YOUR_DISCORD_CHANNEL_ID
  #optional
  mention_users: user1:123456789012345678,user2:987654321098765432
  #default true
  show_version: true
  #default true
  show_flavor: true