name: build_and_send
description: A Dart package for building artifacts, upload and sending them.
version: 1.0.6
repository: https://github.com/mariovtor/build_and_send
homepage: https://github.com/mariovtor/build_and_send
issue_tracker: https://github.com/mariovtor/build_and_send/issues

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  ansi: ^0.4.2
  args: ^2.5.0
  http: '>=0.13.5 <2.0.0'
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
